### ISSUE TITLE
Implement a BTree-backed array

### ISSUE THREAD

**Issue by kevmo314** [kevmo314/appendable#350]
As we talked about, we should back the sequential id -> vector mapping with a b tree. Crucially, we actually need a B Tree now, not a B+ tree. So maybe we screwed up by calling the B+ tree a B tree 🤣 

Anyways, let's create a new package that is very similar to a B+ tree but implements the regular B tree algorithm allowing values to be stored in nodes: https://en.wikipedia.org/wiki/B-tree

```
type BTreeNode struct {
	Vectors     [][]float32 // should be one less than number of pointers
	Pointers []uint64

	// the expected width for the BTree's type
	Width uint16
}
```

**Comment by friendlymatthew** [comment]
> Crucially, we actually need a B Tree now, not a B+ tree. So maybe we screwed up by calling the B+ tree a B tree 🤣

🤣🤣🤣🤣🤣🤣
